### ISSUE TITLE
doesn't build yet with 7.8 

### ISSUE THREAD

**Issue by cartazio** [paf31/pattern-arrows#1]
theres an associated bug on GHC trac related to the matter (others have hit it too)https://ghc.haskell.org/trac/ghc/ticket/8865

**Comment by paf31** [comment]
It looks like a fix was merged into GHC HEAD very recently. Do you think it's worth waiting until the next RC or actual release? If not, maybe the `StandaloneDeriving` workaround can be used.

**Comment by cartazio** [comment]
Honestly, i'll probably try to cherry pick a bunch of the fixes from HEAD and apply them to 7.8

I tried to figure out getting that "standalone" idea to work last night... got a bit ... hairy

**Comment by cartazio** [comment]
i did a test build with my patch with HEAD patches ghc 7.8 RC build, and this lib builds :)

**Comment by paf31** [comment]
Excellent :)
